### ISSUE TITLE
docker compose up fails because nginx.conf does not exist

### ISSUE THREAD

**Issue by wadeholler** [bitnami/bitnami-docker-harbor-registry#1]
fails because nginx.conf does not exist.

Creating chartmuseum               ... done
Creating harbor-helm_registryctl_1 ... done
Creating harbor-db                 ... done
Creating harbor-helm_redis_1       ... done
Creating harbor-helm_registry_1    ... done
Creating harbor-core               ... done
Creating harbor-portal             ... done
Creating harbor-jobservice         ... done
Creating nginx                     ... error

ERROR: for nginx  Cannot start service harbor-nginx: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/san1/projects/harbor-helm/config/proxy/nginx.conf\\\" to rootfs \\\"/san1/docker/overlay2/dc4457d5c1605ba4eb51daa9d2b0c5533fcaa4c0b667ddd27197636712921c75/merged\\\" at \\\"/san1/docker/overlay2/dc4457d5c1605ba4eb51daa9d2b0c5533fcaa4c0b667ddd27197636712921c75/merged/opt/bitnami/nginx/conf/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for harbor-nginx  Cannot start service harbor-nginx: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/san1/projects/harbor-helm/config/proxy/nginx.conf\\\" to rootfs \\\"/san1/docker/overlay2/dc4457d5c1605ba4eb51daa9d2b0c5533fcaa4c0b667ddd27197636712921c75/merged\\\" at \\\"/san1/docker/overlay2/dc4457d5c1605ba4eb51daa9d2b0c5533fcaa4c0b667ddd27197636712921c75/merged/opt/bitnami/nginx/conf/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by marcosbc** [comment]
Hi @wadeholler, if you clone the repository https://github.com/bitnami/bitnami-docker-harbor-portal/ and then run the `docker-compose up` command from the `1/debian-10` directory it should work.

In any case, you're right as the root directory of the repo does not contain the required files. We've just added them and are working to fix the TL;DR instructions so they work too:

```
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-harbor-portal/master/docker-compose.yml
$ curl -L https://github.com/bitnami/bitnami-docker-harbor-portal/archive/master.tar.gz | tar xz --strip=1 --wildcards '*-master/config'
$ docker-compose up
```
