### ISSUE TITLE
bad config link

### ISSUE THREAD

**Issue by xehrad** [bitnami/bitnami-docker-harbor-registry#3]
### Name and Version

 2.5.3-debian-11-r0 release

### What steps will reproduce the bug?

hi dear
at https://github.com/bitnami/bitnami-docker-harbor-portal/archive/master.tar.gz, file "**config**" must be link to "**2/debian-11/config**" but is it "**2/debian-10/config**"

### What is the expected behavior?

config -> 2/debian-11/config

### What do you see instead?

config -> 2/debian-10/config

**Comment by javsalgar** [comment]
Hi!

Thank you so much for reporting! Would you like to submit a PR fixing the link?

**Comment by fmulero** [comment]
This problem is sorted out right now
