### ISSUE TITLE
harbor-registry communication issue with AWS S3 with tls 1.3

### ISSUE THREAD

**Issue by ranjithkumar2106** [bitnami/bitnami-docker-harbor-registry#4]
### Name and Version

bitnami / bitnami-docker-harbor-registry

### What is the problem this feature will solve?

Deploying Harbor in a private EKS cluster with bitnami/harbor helm chart and storage end as AWS S3 bucket. 
- Does this image support communicating to AWS S3 bucket with tls 1.3???

### What is the feature you are proposing to solve the problem?

- Is there anything which i have to enable to configure the communication to S3 bucket with tls 1.3...

**Comment by gongomgra** [comment]
Hi @ranjithkumar2106 ,

Thank you for using our solution. You question is related to the Bitnami Charts and this repo is about the Bitnami VMs. Please create the issue in the correct repository

https://github.com/bitnami/charts

Thanks
